### ISSUE TITLE
Duplicate padding for preformatted text with line numbers

### ISSUE THREAD

**Issue by oofnikj** [vaga/hugo-theme-m10c#54]
Hi, first off thanks for your work on this theme!

When using the `highlight` shortcode with `linenos=table`, the left-hand border appears in both tables.
In addition, a border appears around the table whereas it does not for `linenos=inline` or `linenos=false`:

![Screenshot from 2020-12-30 09-27-51](https://user-images.githubusercontent.com/25017173/103336641-7b039100-4a81-11eb-8c47-b910926ef89a.png)

I work around this with the following SCSS:
```scss
 // get rid of duplicate padding element in pre-formatted content
.post-content td:nth-child(2) pre {
  border: 0;
}

// border around pre-formatted tables
.post-content div.highlight div {
  background-color: unset !important;
}
```

Result:
![Screenshot from 2020-12-30 09-39-30](https://user-images.githubusercontent.com/25017173/103337129-f9acfe00-4a82-11eb-93de-b557ee648120.png)

I think it is more visually consistent to only have the border on the first cell.
There is probably a better way of doing this (especially the `!important` hack - I couldn't get it to work otherwise), but I'm not so good with styling.
