### ISSUE TITLE
Add icon property in social link configuration

### ISSUE THREAD

**Issue by vaga** [vaga/hugo-theme-m10c#59]
- [x] Add `icon` property
- [x] Use `name` property in `<a>` tag title attribute

Example:
```toml
[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/vaga"
```
