### ISSUE TITLE
m10c is not compatible with Hugo v0.104 

### ISSUE THREAD

**Issue by chapimenge3** [vaga/hugo-theme-m10c#94]
I think the current version of the m10c and Hugo is not compatible.  

![image](https://user-images.githubusercontent.com/48279189/198377119-ae6e02c5-b84a-40cb-85b2-56ef1bb929b2.png)

**Comment by chapimenge3** [comment]
@kachick have you got any workaround ?

**Comment by kachick** [comment]
I use extended version when using this theme. 🙇‍♂️ 
And switching the versions with asdf.

When I use https://github.com/peaceiris/actions-hugo, I use following config

```yaml
- uses: actions/checkout@v3
  with:
    submodules: true
    fetch-depth: 0
- name: Setup Hugo
  uses: peaceiris/actions-hugo@v2
  with:
    extended: true
```
